version: '3.8'

services:
  testes-bdd-ger_de_traf:
    build:
      context: .
      dockerfile: Dockerfile
    image: testes-bdd-ger_de_traf:latest
    entrypoint: ["mvn", "clean", "test"]
    environment:
      - API_HOST=http://traffic-incident-management-api:8080
    networks:
      - trafego-net

networks:
  trafego-net:
    external: true
